/**
 * @file Provides a basic timer util for logger.
 *
 * @author: Leo Wang (wangkemiao@baidu.com)
 */

define(function(require) {
    /**
     * The cache of the timer.
     *
     * @type {Object}
     */
    var data = {};

    /**
     * The object to be exported.
     */
    var timer = {};

    /**
     * Starts the timer with a key.
     *
     * @param {?string} opt_key The key of the timer.
     * @return {string} The key that passed in by parameter or generated by
     *     the function.
     */
    timer.start = function(opt_key) {
        var now = +(new Date());
        var key = opt_key || ('KEY' + now);
        data[key] = now;
        return key;
    };

    /**
     * Ends the timer with a key.
     *
     * @param {string} key The key of the timer.
     * @return {number} Return the time ellapse, or -1 if key doesn't exist.
     */
    timer.stop = function(key) {
        if (data[key]) {
            var now = +(new Date());
            var started = data[key];
            data[key] = null;
            return now - started;
        }
        return -1;
    };

    return timer;
});
